[tool.poetry]
name = "nav_components"
version = "0.1.1"
description = ""
authors = ["wwwshwww <www.shinderu.www@gmail.com>"]
build = "build.py"

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
numpy = "^1.21.2"
cython = "^0.29.24"

[tool.poetry.dev-dependencies]
matplotlib = "^3.4.3"
pygame = "^2.1.0"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0", "cython", "numpy"]
build-backend = "poetry.core.masonry.api"
