[tool.poetry]
name = "itba_cde_tpf_python_applications_fvidal90"
version = "0.3.0"
description = "TP Vidal"
authors = ["Fernando Vidal <picovidal22@gmail.com>"]
packages = [
    { include = "create_tables" },
    { include = "db_api_client" },
]
[tool.poetry.dependencies]
python = "^3.9"
pandas = "1.3.4"
requests = "2.26.0"
SQLAlchemy = "1.4.27"
psycopg2-binary = "2.9.2"
plotly = "^5.4.0"
kaleido = "0.2.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
requests-mock = "^1.9.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
