[username]
disabled = true

[hostname]
disabled = true

[conda]
format = "\\([$environment]($style)\\) "
ignore_base = false

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸ”ºÃ—$count "
behind = "ğŸ”»Ã—$count "
diverged = "ğŸ”€ ğŸ”ºÃ—${ahead_count} ğŸ”»Ã—${behind_count} "
untracked = "ğŸ”“Ã—$count "
stashed = "ğŸ“¥ "
modified = "ğŸ“Ã—$count "
staged = "ğŸ”’Ã—$count "
renamed = ""
deleted = "ğŸ”¥Ã—$count "
style = "bright-white"
format = "$all_status$ahead_behind"